### ISSUE TITLE
Keeping player scores

### ISSUE THREAD

**Issue by chavi362** [chavi362/Get-to-100-#3]
I would like to keep the player scores in the local storage.
For that I need that after one finish a game it will add the steps as the score to the scores array

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by IrfanSalim** [comment]
I dont understand the point of this, in the game the max move is 1, if its wrong buttons get disabled and if its right, you win.

The random number is 99 for all games, and one move to win. Not sure if this is by design?

Can you please elaborate a bit on the expectations?

**Comment by IrfanSalim** [comment]
Also, can you explain what is the purpose of disabling the buttons?

**Comment by chavi362** [comment]
I want that the game will be in turns so each time the all players will be disabled unsles he player that is on its turn.
The random number is 99 for all games, and one move to win because we did it for testing because we don't ant to work  each time for coming to win.
But now I'm changing it.
If you like you can do it for yourself so it willl be easy to debug.
@IrfanSalim , Can you please do it soon?
Becaus I need this for continuing the project
Thank you very much😊👍

**Comment by chavi362** [comment]
Hi @IrfanSalim , first of all, thank you very much for the work!!! I really Appreciate it!
I really have to move forward with the project and present the leading actors.
So I need the scores to be updated as soon as one of the games is finished.
Can you do it for another 3 hours?

**Comment by IrfanSalim** [comment]
Yes, working on it

**Comment by IrfanSalim** [comment]
@chavi362 Please check this

**Comment by efratMIL** [comment]
Thank you veryy much we really appreciate it...
please share this reporsity and star it ..
😁😁
